"""Deleted Both Test

Revision ID: f0a854f1cd51
Revises: 0cf806f33b65
Create Date: 2023-08-19 12:27:34.844720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0a854f1cd51'
down_revision: Union[str, None] = '0cf806f33b65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'test')
    op.drop_column('votes', 'test')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('test', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('test', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
